language: node_js
cache: 
directories:
- node_modules
notifications:
  email: true
node_js:
- '8'
env:
  global:
    secure: qKb54z3jKHmjppFfYWCuErZXWrBwLNtCcQ0yFbCwfFLxCRXkZl4gIFehwhIDHEYDF32lDEQXah8LOKzuNmo3epkJi5QVjz//xcJwUDearLVR16DuCAg9E3NDiZxG8U2raN2kXjiZFxpeITyAclAzW7wmMi5CqEp918EPumyOmgLo7xaD2UrrwKtSQhk9IU2viYukGD4+x3KOPfRy2xaCfVMpJ8R2yIUuXg/aBNWiGr2QV5JcPgRE5IATCpzXBssxd6Wp52xXZrCSzQlTKUjuw06L7xaQvQmGF5vCR/mwo5mK2W6HYmSo3sLKVdIRWuan2Q8hzIabBksZY8qUjHNXVNWTg5Ovhn0kjCH4njTfesYUwhXX0tReyscZkWlBNVKJqxkP1BsSgp7z9FmUFwN01EDeDlaoiX37soq2Iq0QUNIk0O1lhuOkfrpR694hWHXl/eg9vxbmG1sxKhFZ1Uesx9vkGjhTEWq6jvTcWRbOu3TY7u18RorQJUWfA9wf1FYibtuMOpR3+bFEoFdc/8GOuEcAxiOiyW3CwxRvxPpaVTzYq+i/ZDr0wWFeML7Vy9NthKNAgkXad6J4NZrLiGEJMIpB263oS5i1iZwM77HAK6TvW+PweHKy/ebeNzXMQt/t02+rZSt5CxqlKvJUYf6GaUxSqKprYFW93TmyWJ/b3Tk=
